version: '3'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    environment:
      - DEFAULT_HOST=t1.sysadm.com
     
 ######### whoami sample images#######  
  whoami:
    image: containous/whoami
    labels:
      - traefik.backend=whoami
      - traefik.frontend.rule=Host:whoami.t1.sysadm.com
      - traefik.docker.network=web
      - traefik.port=80 
 ###################Racktables #########################
  racktables:
        container_name: racktables
        restart: unless-stopped
        volumes:
            - '/opt/racktables/secret.php:/var/www/html/inc/secret.php'
        image: thinfactory/racktables
        labels:
          - traefik.backend=racktables
          - traefik.frontend.rule=Host:dcasset.t1.sysadm.com
          - traefik.docker.network=web
          - traefik.port=80
####################### mariadb #####################################
 
 db:
    image: mariadb
    restart: always
    container_name: mariadbprd
    environment:
      MYSQL_ROOT_PASSWORD: apple@123
    volumes:
      - '/var/roothome/docpool/mariadbdata:/var/lib/mysql'
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:mariadb.t1.sysadm.com
########################## els and kibana ################
 elasticsearch:
    image: elasticsearch:7.0.1
    container_name: elsprd
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    
  kibana:
    image: kibana:7.0.1
    container_name: kibanaprd
    ports:
      - "5601:5601"
    volumes:
      - '/var/roothome/docpool/esdata:/usr/share/elasticsearch/data'
    labels:
      - traefik.enable=true
      - traefik.backend=elsbckend
      - traefik.frontend.rule=Host:elsprd.t1.sysadm.com
      
networks:
  default:
    external:
      name: web
