defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.traefik]
  address = ":8080"
    [entryPoints.traefik.auth.basic]
    users = ["admin:$apr1$BY818Y1x$VN.vSBGGYYqFs9qxDZi/h0"]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[api]
entryPoint = "traefik"

