version: "3"
services:
  whoami:
    image: containous/whoami
    labels:
      - traefik.backend=whoami
      - traefik.frontend.rule=Host:whoami.t1.sysadm.com
      - traefik.docker.network=web
      - traefik.port=80
networks:
  default:
    external:
      name: web
