# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    container_name: mariadbprd
    environment:
      MYSQL_ROOT_PASSWORD: apple@123
    volumes:
      - '/var/roothome/docpool/mariadbdata:/var/lib/mysql'
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:mariadb.t1.sysadm.com
networks:
  default:
    external:
      name: web
